/**
 * Channel Abstraction Layer — Unified messaging channel interface for OpenVera.
 *
 * Provides a ChannelAdapter interface that abstracts over different messaging
 * platforms (CLI, REST API, Webhook, Feishu, Slack, etc.) so that agents can
 * send and receive messages uniformly regardless of the underlying platform.
 */

// ── Channel Message Types ────────────────────────────────────────────────────

/** Supported channel/platform types */
export type ChannelType =
  | "cli"
  | "api"
  | "webhook"
  | "feishu"
  | "wecom"
  | "telegram"
  | "discord"
  | "slack"
  | "whatsapp"
  | "custom";

/** Attachment in a channel message */
export interface ChannelAttachment {
  /** Attachment type */
  type: "image" | "file" | "audio" | "video" | "link";
  /** Attachment URL or local path */
  url: string;
  /** Original filename */
  name?: string;
  /** MIME type */
  mimeType?: string;
  /** File size in bytes */
  sizeBytes?: number;
}

/** Unified message format across all channels */
export interface ChannelMessage {
  /** Unique message ID (generated by the channel or the adapter) */
  id: string;
  /** The channel/platform this message belongs to */
  channelType: ChannelType;
  /** Sender identifier (user ID, username, etc.) */
  senderId: string;
  /** Sender display name (optional, for rendering) */
  senderName?: string;
  /** Message text content */
  content: string;
  /** Attachments (images, files, etc.) */
  attachments: ChannelAttachment[];
  /** ID of the message this is replying to (optional) */
  replyTo?: string;
  /** ISO timestamp of the message */
  timestamp: string;
  /** Channel-specific raw payload (for advanced use) */
  raw?: unknown;
}

// ── Connection State ─────────────────────────────────────────────────────────

/** Connection state of a channel adapter */
export type ConnectionState = "disconnected" | "connecting" | "connected" | "error";

/** Connection status with optional detail */
export interface ChannelStatus {
  state: ConnectionState;
  /** Human-readable status message */
  message?: string;
  /** ISO timestamp of last state change */
  changedAt: string;
  /** Number of messages sent since connection */
  sentCount: number;
  /** Number of messages received since connection */
  receivedCount: number;
}

// ── Channel Adapter Interface ────────────────────────────────────────────────

/** Callback for incoming messages */
export type MessageCallback = (message: ChannelMessage) => void | Promise<void>;

/** Options for sending a message */
export interface SendMessageOptions {
  /** Message text content */
  content: string;
  /** Attachments to include */
  attachments?: ChannelAttachment[];
  /** ID of the message to reply to */
  replyTo?: string;
  /** Channel-specific options (e.g., parse_mode for Telegram) */
  channelOptions?: Record<string, unknown>;
}

/** Options for retrieving message history */
export interface HistoryOptions {
  /** Maximum number of messages to retrieve */
  limit?: number;
  /** Retrieve messages after this timestamp (ISO) */
  after?: string;
  /** Retrieve messages before this timestamp (ISO) */
  before?: string;
  /** Filter by sender ID */
  senderId?: string;
}

/**
 * Core channel adapter interface. All platform adapters (CLI, REST, webhook,
 * Feishu, Slack, etc.) implement this interface for uniform message handling.
 */
export interface ChannelAdapter {
  /** Unique name of this adapter (e.g., "cli", "feishu", "slack") */
  readonly name: string;

  /** The channel type this adapter handles */
  readonly channelType: ChannelType;

  /** Current connection state */
  readonly state: ConnectionState;

  // ── Lifecycle ────────────────────────────────────────────────────────────

  /** Connect to the channel (establish WebSocket, start HTTP listener, etc.) */
  connect(): Promise<void>;

  /** Disconnect from the channel and release resources */
  disconnect(): Promise<void>;

  /** Get detailed connection status */
  getStatus(): ChannelStatus;

  // ── Messaging ────────────────────────────────────────────────────────────

  /** Send a message through the channel */
  sendMessage(options: SendMessageOptions): Promise<ChannelMessage>;

  /** Register a callback for incoming messages */
  onMessage(callback: MessageCallback): () => void;

  /** Retrieve message history */
  getHistory(options?: HistoryOptions): Promise<ChannelMessage[]>;
}

// ── Gateway Types ────────────────────────────────────────────────────────────

/** Configuration for the Channel Gateway */
export interface GatewayConfig {
  /** Maximum number of concurrent channel connections */
  maxConnections?: number;
  /** Default message timeout in milliseconds */
  defaultTimeoutMs?: number;
  /** Whether to auto-reconnect on disconnection */
  autoReconnect?: boolean;
  /** Reconnect interval in milliseconds */
  reconnectIntervalMs?: number;
  /** Maximum reconnect attempts (0 = unlimited) */
  maxReconnectAttempts?: number;
}

/** Event emitted by the Gateway */
export type GatewayEvent =
  | { type: "channel_connected"; channelName: string }
  | { type: "channel_disconnected"; channelName: string; reason?: string }
  | { type: "channel_error"; channelName: string; error: string }
  | { type: "message_received"; channelName: string; message: ChannelMessage }
  | { type: "message_sent"; channelName: string; message: ChannelMessage }
  | { type: "reconnecting"; channelName: string; attempt: number };

/** Callback for gateway events */
export type GatewayEventCallback = (event: GatewayEvent) => void | Promise<void>;

// ── Error Types ──────────────────────────────────────────────────────────────

export class ChannelError extends Error {
  readonly code: string;

  constructor(code: string, message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = "ChannelError";
    this.code = code;
  }
}

export class ChannelConnectionError extends ChannelError {
  constructor(channelName: string, detail: string, options?: ErrorOptions) {
    super("CHANNEL_CONNECTION", `Connection failed for ${channelName}: ${detail}`, options);
    this.name = "ChannelConnectionError";
  }
}

export class ChannelSendError extends ChannelError {
  constructor(channelName: string, detail: string, options?: ErrorOptions) {
    super("CHANNEL_SEND", `Send failed for ${channelName}: ${detail}`, options);
    this.name = "ChannelSendError";
  }
}

export class ChannelTimeoutError extends ChannelError {
  constructor(channelName: string, timeoutMs: number) {
    super("CHANNEL_TIMEOUT", `Operation timed out for ${channelName} after ${timeoutMs}ms`);
    this.name = "ChannelTimeoutError";
  }
}

export class ChannelNotConnectedError extends ChannelError {
  constructor(channelName: string) {
    super("CHANNEL_NOT_CONNECTED", `Channel ${channelName} is not connected`);
    this.name = "ChannelNotConnectedError";
  }
}

export class ChannelNotFoundError extends ChannelError {
  constructor(channelName: string) {
    super("CHANNEL_NOT_FOUND", `Channel not found: ${channelName}`);
    this.name = "ChannelNotFoundError";
  }
}
