import { completeColorTokens, type ThemeColorInput, type ThemeColorTokens } from "./tokens.js";
import type { BuiltinWallpaperId } from "./wallpapers.js";

export type ResolvedThemeId =
  | "cursor"
  | "github-dark"
  | "github-light"
  | "graphite"
  | "graphite-light"
  | "midnight"
  | "zinc"
  | "book"
  | "inkwash"
  | "worldcup"
  | "ayaka-night"
  | "ayaka-frost";

export type AppThemeId = "system" | "custom" | ResolvedThemeId;

export interface ThemeDefinition {
  id: ResolvedThemeId;
  labelZh: string;
  labelEn: string;
  scheme: "light" | "dark";
  colors: ThemeColorTokens;
  /** Optional builtin wallpaper attached when wallpaperMode=theme */
  wallpaper?: BuiltinWallpaperId;
}

function theme(
  def: Omit<ThemeDefinition, "colors"> & { colors: ThemeColorInput },
): ThemeDefinition {
  return {
    ...def,
    colors: completeColorTokens(def.colors),
  };
}

export const THEME_REGISTRY: Record<ResolvedThemeId, ThemeDefinition> = {
  "github-dark": theme({
    id: "github-dark",
    labelZh: "GitHub Dark",
    labelEn: "GitHub Dark",
    scheme: "dark",
    colors: {
      bg: "#0d1117",
      surface: "#161b22",
      surfaceElevated: "#161b22",
      surfaceInset: "#010409",
      surfaceHover: "#21262d",
      border: "#30363d",
      text: "#e6edf3",
      textMuted: "#9198a1",
      accent: "#58a6ff",
      accentText: "#ffffff",
      tabIndicator: "#f78166",
      danger: "#f85149",
      dangerMuted: "#ff7b72",
      success: "#3fb950",
      successEmphasis: "#238636",
      attention: "#d29922",
      tokenComment: "#8b949e",
      tokenKeyword: "#ff7b72",
      tokenString: "#a5d6ff",
      tokenVariable: "#ffa657",
      tokenProperty: "#79c0ff",
      tokenNumber: "#79c0ff",
    },
  }),
  "github-light": theme({
    id: "github-light",
    labelZh: "GitHub Light",
    labelEn: "GitHub Light",
    scheme: "light",
    colors: {
      bg: "#ffffff",
      surface: "#f6f8fa",
      surfaceElevated: "#ffffff",
      surfaceInset: "#f6f8fa",
      surfaceHover: "#eaeef2",
      border: "#d0d7de",
      text: "#1f2328",
      textMuted: "#59636e",
      accent: "#0969da",
      accentText: "#ffffff",
      tabIndicator: "#fd8c73",
      danger: "#cf222e",
      dangerMuted: "#a40e26",
      success: "#1a7f37",
      successEmphasis: "#1f883d",
      attention: "#9a6700",
    },
  }),
  cursor: theme({
    id: "cursor",
    labelZh: "Cursor",
    labelEn: "Cursor",
    scheme: "dark",
    colors: {
      bg: "#181818",
      surface: "#141414",
      surfaceElevated: "#1f1f1f",
      surfaceInset: "#141414",
      surfaceHover: "#2a2a2a",
      border: "#2b2b2b",
      text: "#e6e6e6",
      textMuted: "#9b9b9b",
      accent: "#81c7bb",
      accentText: "#141414",
      danger: "#f07178",
      dangerMuted: "#ff8b92",
      success: "#7fd992",
      successEmphasis: "#3d9c5c",
      attention: "#e6c07b",
      tokenComment: "#6b6b6b",
      tokenKeyword: "#c3a6e0",
      tokenString: "#9eceb0",
      tokenVariable: "#e6c07b",
      tokenProperty: "#d4a0c0",
      tokenNumber: "#f0a07a",
    },
  }),
  graphite: theme({
    id: "graphite",
    labelZh: "石墨深色",
    labelEn: "Graphite",
    scheme: "dark",
    colors: {
      bg: "#202124",
      surface: "#292a2d",
      surfaceElevated: "#1f2023",
      surfaceInset: "#1a1b1e",
      surfaceHover: "#303134",
      border: "#3c4043",
      text: "#e8eaed",
      textMuted: "#9aa0a6",
      accent: "#8ab4f8",
      accentText: "#202124",
      danger: "#f28b82",
      dangerMuted: "#ff8a8a",
      success: "#81c995",
      successEmphasis: "#137333",
      attention: "#fdd663",
    },
  }),
  "graphite-light": theme({
    id: "graphite-light",
    labelZh: "石墨浅色",
    labelEn: "Graphite Light",
    scheme: "light",
    colors: {
      bg: "#f8fafd",
      surface: "#ffffff",
      surfaceElevated: "#f1f3f4",
      surfaceInset: "#f1f3f4",
      surfaceHover: "#e8eaed",
      border: "#dadce0",
      text: "#202124",
      textMuted: "#5f6368",
      accent: "#1a73e8",
      accentText: "#ffffff",
      danger: "#d93025",
      dangerMuted: "#c5221f",
      success: "#188038",
      successEmphasis: "#137333",
      attention: "#e37400",
    },
  }),
  midnight: theme({
    id: "midnight",
    labelZh: "午夜蓝",
    labelEn: "Midnight",
    scheme: "dark",
    colors: {
      bg: "#0b1220",
      surface: "#111827",
      surfaceElevated: "#1a2336",
      surfaceInset: "#070d18",
      surfaceHover: "#1f2937",
      border: "#243044",
      text: "#e5e7eb",
      textMuted: "#9ca3af",
      accent: "#38bdf8",
      accentText: "#0b1220",
      danger: "#f87171",
      dangerMuted: "#fca5a5",
      success: "#34d399",
      successEmphasis: "#059669",
      attention: "#fbbf24",
    },
  }),
  zinc: theme({
    id: "zinc",
    labelZh: "锌灰紫",
    labelEn: "Zinc",
    scheme: "dark",
    colors: {
      bg: "#09090b",
      surface: "#18181b",
      surfaceElevated: "#18181b",
      surfaceInset: "#09090b",
      surfaceHover: "#27272a",
      border: "#3f3f46",
      text: "#fafafa",
      textMuted: "#a1a1aa",
      accent: "#a78bfa",
      accentText: "#09090b",
      danger: "#f87171",
      dangerMuted: "#fca5a5",
      success: "#4ade80",
      successEmphasis: "#16a34a",
      attention: "#facc15",
    },
  }),
  book: theme({
    id: "book",
    labelZh: "书卷",
    labelEn: "Book",
    scheme: "light",
    wallpaper: "book",
    colors: {
      // Aged parchment: dimmer, less yellow, more dusty sepia
      bg: "#c7b69a",
      surface: "#b9a78a",
      surfaceElevated: "#d2c3a8",
      surfaceInset: "#a9977a",
      surfaceHover: "#ae9b7e",
      border: "#7d6a52",
      text: "#241c14",
      textMuted: "#5c4c3a",
      accent: "#5c3a1e",
      accentText: "#e6d8c0",
      tabIndicator: "#5c3a1e",
      danger: "#7a2e22",
      dangerMuted: "#9a4536",
      success: "#3d5c45",
      successEmphasis: "#2f4a36",
      attention: "#8a6a32",
      tokenComment: "#6e5c48",
      tokenKeyword: "#6b2e22",
      tokenString: "#35503c",
      tokenVariable: "#7a5a28",
      tokenProperty: "#4a3828",
      tokenNumber: "#7a4224",
    },
  }),
  inkwash: theme({
    id: "inkwash",
    labelZh: "水墨",
    labelEn: "Ink Wash",
    scheme: "light",
    wallpaper: "inkwash",
    colors: {
      bg: "#e8e4dc",
      surface: "#f2efe8",
      surfaceElevated: "#f7f5f0",
      surfaceInset: "#ddd7cc",
      surfaceHover: "#d9d3c8",
      border: "#b8b2a8",
      text: "#1c1c1c",
      textMuted: "#5c5c5c",
      accent: "#2a2a2a",
      accentText: "#f2efe8",
      danger: "#6b2a2a",
      dangerMuted: "#8a3d3d",
      success: "#3d5c45",
      successEmphasis: "#2f4a36",
      attention: "#6b5a32",
      tokenComment: "#7a756c",
      tokenKeyword: "#1a1a1a",
      tokenString: "#3a4a3f",
      tokenVariable: "#4a4030",
      tokenProperty: "#2f2f2f",
      tokenNumber: "#4a3830",
    },
  }),
  worldcup: theme({
    id: "worldcup",
    labelZh: "世界杯",
    labelEn: "World Cup",
    scheme: "light",
    wallpaper: "worldcup",
    // Pulled from wallpapers/worldcup.png: sky blue / pitch green / jersey red / kit yellow
    colors: {
      bg: "#d8eefc",
      surface: "#f3faf6",
      surfaceElevated: "#ffffff",
      surfaceInset: "#c5e4f7",
      surfaceHover: "#b7dcf3",
      border: "#7eb6d9",
      text: "#12324a",
      textMuted: "#4a6d82",
      accent: "#e53935",
      accentText: "#ffffff",
      tabIndicator: "#f2c94c",
      danger: "#d32f2f",
      dangerMuted: "#ef5350",
      success: "#2e9b4a",
      successEmphasis: "#1d8348",
      attention: "#f2c94c",
      tokenComment: "#5f7d8c",
      tokenKeyword: "#e53935",
      tokenString: "#1d8348",
      tokenVariable: "#1e88e5",
      tokenProperty: "#1565c0",
      tokenNumber: "#f9a825",
    },
  }),
  "ayaka-night": theme({
    id: "ayaka-night",
    labelZh: "夜樱",
    labelEn: "Night Bloom",
    scheme: "dark",
    wallpaper: "ayaka-night",
    colors: {
      bg: "#0d0d10",
      surface: "#16161b",
      surfaceElevated: "#1d1d24",
      surfaceInset: "#0a0a0d",
      surfaceHover: "#26262f",
      border: "#34343f",
      text: "#e4e7f0",
      textMuted: "#969aad",
      accent: "#c45c6a",
      accentText: "#ffffff",
      tabIndicator: "#c9a45c",
      danger: "#c45c6a",
      dangerMuted: "#e08a96",
      success: "#6f9e86",
      successEmphasis: "#4f7d66",
      attention: "#c9a45c",
      tokenComment: "#7d8194",
      tokenKeyword: "#e08a96",
      tokenString: "#b0c4de",
      tokenVariable: "#c9a45c",
      tokenProperty: "#b0c4de",
      tokenNumber: "#d4a574",
    },
  }),
  "ayaka-frost": theme({
    id: "ayaka-frost",
    labelZh: "霜华",
    labelEn: "Frost Bloom",
    scheme: "light",
    wallpaper: "ayaka-frost",
    colors: {
      bg: "#f4f7fb",
      surface: "#ffffff",
      surfaceElevated: "#ffffff",
      surfaceInset: "#e8eef6",
      surfaceHover: "#e4ebf4",
      border: "#c9d6e6",
      text: "#2a3344",
      textMuted: "#6b7a8f",
      accent: "#e091a3",
      accentText: "#ffffff",
      tabIndicator: "#7eb0d4",
      danger: "#c45c6a",
      dangerMuted: "#d87a88",
      success: "#5a9a7a",
      successEmphasis: "#3f7a5c",
      attention: "#d4a45c",
      tokenComment: "#8a96a8",
      tokenKeyword: "#e091a3",
      tokenString: "#5a8fbf",
      tokenVariable: "#7eb0d4",
      tokenProperty: "#6b7a8f",
      tokenNumber: "#c9a45c",
    },
  }),
};

/** UI order for the settings theme picker (presets only; custom lives under wallpaper). */
export const THEME_ORDER: Array<Exclude<AppThemeId, "custom">> = [
  "system",
  "cursor",
  "github-dark",
  "github-light",
  "ayaka-night",
  "ayaka-frost",
  "book",
  "inkwash",
  "worldcup",
  "graphite",
  "graphite-light",
  "midnight",
  "zinc",
];

export function getThemeDefinition(id: ResolvedThemeId): ThemeDefinition {
  return THEME_REGISTRY[id];
}

export function isResolvedThemeId(value: unknown): value is ResolvedThemeId {
  return typeof value === "string" && value in THEME_REGISTRY;
}
