import { vi, describe, it, expect, beforeEach } from "vitest";

// ── Hoisted mock state ──────────────────────────────────────────────────────

const { mockGitResponses, mockAccessResults } = vi.hoisted(() => {
  const mockGitResponses = new Map<
    string,
    { stdout: string; code: number }
  >();
  const mockAccessResults = new Map<string, boolean>();
  return { mockGitResponses, mockAccessResults };
});

// ── Mocks ────────────────────────────────────────────────────────────────────

vi.mock("node:child_process", () => ({
  execFile: vi.fn(
    (_file: string, args: string[], _options: unknown, callback: unknown) => {
      // For promisify: callback is the last argument auto-generated by util.promisify
      if (typeof callback === "function") {
        const key = args.join(" ");
        const response = mockGitResponses.get(key);
        if (response) {
          if (response.code === 0) {
            callback(null, { stdout: response.stdout }, "");
          } else {
            const err = Object.assign(new Error("git failed"), {
              code: response.code,
              stdout: response.stdout,
            });
            callback(err, "", "");
          }
        } else {
          // Default: command succeeds with empty stdout
          callback(null, { stdout: "" }, "");
        }
      }
    }
  ),
}));

vi.mock("node:fs/promises", () => ({
  access: vi.fn((path: string) => {
    if (mockAccessResults.get(path)) {
      return Promise.resolve();
    }
    return Promise.reject(Object.assign(new Error("ENOENT"), { code: "ENOENT" }));
  }),
}));

// ── Import module under test ─────────────────────────────────────────────────
// Must happen AFTER vi.mock calls, but vitest hoists them.

import {
  parseGitNumstat,
  parseShortstat,
  parseGitDiff,
  fetchGitDiff,
  fetchGitDiffHunks,
} from "../gitDiff.js";
import type { GitDiffResult } from "../gitDiff.js";
import type { StructuredPatchHunk } from "diff";

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Configure a mocked git command response */
function setGitResponse(
  args: string[],
  stdout: string,
  code = 0
): void {
  mockGitResponses.set(args.join(" "), { stdout, code });
}

/** Configure mocked access() result for a path */
function setAccessResult(path: string, exists: boolean): void {
  mockAccessResults.set(path, exists);
}

/** Reset all mock state */
function resetMocks(): void {
  mockGitResponses.clear();
  mockAccessResults.clear();
}

beforeEach(() => {
  resetMocks();
});

// ── parseGitNumstat ──────────────────────────────────────────────────────────

describe("parseGitNumstat", () => {
  it("returns zero stats for empty input", () => {
    const result = parseGitNumstat("");
    expect(result.stats).toEqual({
      filesCount: 0,
      linesAdded: 0,
      linesRemoved: 0,
    });
    expect(result.perFileStats.size).toBe(0);
  });

  it("returns zero stats for whitespace-only input", () => {
    const result = parseGitNumstat("  \n  \n  ");
    expect(result.stats.filesCount).toBe(0);
    expect(result.perFileStats.size).toBe(0);
  });

  it("parses a single file with normal add/remove", () => {
    const stdout = "5\t3\tsrc/index.ts\n";
    const result = parseGitNumstat(stdout);
    expect(result.stats).toEqual({
      filesCount: 1,
      linesAdded: 5,
      linesRemoved: 3,
    });
    expect(result.perFileStats.size).toBe(1);
    const fileStat = result.perFileStats.get("src/index.ts");
    expect(fileStat).toEqual({
      added: 5,
      removed: 3,
      isBinary: false,
    });
  });

  it("sums add/remove across multiple files", () => {
    const stdout = [
      "10\t2\tsrc/a.ts",
      "5\t8\tsrc/b.ts",
      "0\t1\tsrc/c.ts",
    ].join("\n");
    const result = parseGitNumstat(stdout);
    expect(result.stats).toEqual({
      filesCount: 3,
      linesAdded: 15,
      linesRemoved: 11,
    });
    expect(result.perFileStats.size).toBe(3);
  });

  it("handles zero add and zero remove", () => {
    const stdout = "0\t0\tsrc/empty.ts\n";
    const result = parseGitNumstat(stdout);
    expect(result.stats).toEqual({
      filesCount: 1,
      linesAdded: 0,
      linesRemoved: 0,
    });
    const fileStat = result.perFileStats.get("src/empty.ts");
    expect(fileStat).toEqual({
      added: 0,
      removed: 0,
      isBinary: false,
    });
  });

  it("marks file as binary when add column is '-'", () => {
    const stdout = "-\t-\tassets/logo.png\n";
    const result = parseGitNumstat(stdout);
    expect(result.stats.filesCount).toBe(1);
    expect(result.stats.linesAdded).toBe(0);
    expect(result.stats.linesRemoved).toBe(0);
    expect(result.perFileStats.get("assets/logo.png")).toEqual({
      added: 0,
      removed: 0,
      isBinary: true,
    });
  });

  it("marks file as binary when remove column is '-'", () => {
    const stdout = "100\t-\tassets/icon.bin\n";
    const result = parseGitNumstat(stdout);
    expect(result.stats.filesCount).toBe(1);
    expect(result.stats.linesRemoved).toBe(0);
    expect(result.perFileStats.get("assets/icon.bin")!.isBinary).toBe(true);
  });

  it("handles files with tabs in names (3-part split with tabs)", () => {
    // A file path that contains tabs — parts[2] and beyond are joined
    const stdout = "1\t2\tfile\twith\ttabs.ts\n";
    const result = parseGitNumstat(stdout);
    expect(result.stats.filesCount).toBe(1);
    // The full path should be preserved with tabs
    expect(result.perFileStats.has("file\twith\ttabs.ts")).toBe(true);
    expect(result.perFileStats.get("file\twith\ttabs.ts")).toEqual({
      added: 1,
      removed: 2,
      isBinary: false,
    });
  });

  it("caps perFileStats at MAX_FILES (50)", () => {
    const lines: string[] = [];
    for (let i = 0; i < 60; i++) {
      lines.push(`1\t0\tfile${i}.ts`);
    }
    const stdout = lines.join("\n");
    const result = parseGitNumstat(stdout);
    // Total stats should count all 60 files
    expect(result.stats.filesCount).toBe(60);
    expect(result.stats.linesAdded).toBe(60);
    // But perFileStats should be capped at 50
    expect(result.perFileStats.size).toBe(50);
  });

  it("skips lines with less than 3 tab-separated parts", () => {
    const stdout = [
      "5\t3\tsrc/valid.ts",
      "incomplete\tline",
      "also-incomplete",
      "10\t0\tsrc/another.ts",
    ].join("\n");
    const result = parseGitNumstat(stdout);
    expect(result.stats.filesCount).toBe(2);
    expect(result.perFileStats.size).toBe(2);
    expect(result.perFileStats.has("src/valid.ts")).toBe(true);
    expect(result.perFileStats.has("src/another.ts")).toBe(true);
  });

  it("handles large numbers for add/remove", () => {
    const stdout = "99999\t88888\tsrc/big-change.ts\n";
    const result = parseGitNumstat(stdout);
    expect(result.stats.linesAdded).toBe(99999);
    expect(result.stats.linesRemoved).toBe(88888);
  });

  it("handles non-numeric add/remove values (eg, '-') correctly in sums", () => {
    const stdout = [
      "10\t5\tsrc/normal.ts",
      "-\t-\tassets/binary.png",
      "3\t1\tsrc/small.ts",
    ].join("\n");
    const result = parseGitNumstat(stdout);
    // Binary files contribute 0 to the total
    expect(result.stats.linesAdded).toBe(13);
    expect(result.stats.linesRemoved).toBe(6);
    expect(result.stats.filesCount).toBe(3);
  });

  it("handles trailing newlines", () => {
    const stdout = "1\t2\tsrc/file.ts\n\n";
    const result = parseGitNumstat(stdout);
    expect(result.stats.filesCount).toBe(1);
  });
});

// ── parseShortstat ───────────────────────────────────────────────────────────

describe("parseShortstat", () => {
  it('parses "5 files changed, 10 insertions(+), 3 deletions(-)"', () => {
    const result = parseShortstat(
      "5 files changed, 10 insertions(+), 3 deletions(-)"
    );
    expect(result).toEqual({
      filesCount: 5,
      linesAdded: 10,
      linesRemoved: 3,
    });
  });

  it('parses "1 file changed, 1 insertion(+), 1 deletion(-)" (singular)', () => {
    const result = parseShortstat(
      "1 file changed, 1 insertion(+), 1 deletion(-)"
    );
    expect(result).toEqual({
      filesCount: 1,
      linesAdded: 1,
      linesRemoved: 1,
    });
  });

  it('handles "1 file changed" only (no insertions/deletions)', () => {
    const result = parseShortstat("1 file changed");
    expect(result).toEqual({
      filesCount: 1,
      linesAdded: 0,
      linesRemoved: 0,
    });
  });

  it('handles "2 files changed, 5 insertions(+)" only (no deletions)', () => {
    const result = parseShortstat("2 files changed, 5 insertions(+)");
    expect(result).toEqual({
      filesCount: 2,
      linesAdded: 5,
      linesRemoved: 0,
    });
  });

  it("returns null for no match", () => {
    expect(parseShortstat("")).toBeNull();
    expect(parseShortstat("garbage output")).toBeNull();
    expect(parseShortstat("fatal: not a git repository")).toBeNull();
  });

  it("returns null for empty string", () => {
    expect(parseShortstat("")).toBeNull();
  });

  it("handles large values", () => {
    const result = parseShortstat(
      "1200 files changed, 50000 insertions(+), 30000 deletions(-)"
    );
    expect(result).toEqual({
      filesCount: 1200,
      linesAdded: 50000,
      linesRemoved: 30000,
    });
  });

  it("handles extra whitespace", () => {
    const result = parseShortstat(
      "  3   files   changed,   7   insertions(+),   2   deletions(-)  "
    );
    expect(result).toEqual({
      filesCount: 3,
      linesAdded: 7,
      linesRemoved: 2,
    });
  });
});

// ── parseGitDiff ─────────────────────────────────────────────────────────────

describe("parseGitDiff", () => {
  it("returns empty Map for empty input", () => {
    const result = parseGitDiff("");
    expect(result).toBeInstanceOf(Map);
    expect(result.size).toBe(0);
  });

  it("returns empty Map for whitespace-only input", () => {
    const result = parseGitDiff("  \n  ");
    expect(result).toBeInstanceOf(Map);
    expect(result.size).toBe(0);
  });

  it("parses single file with one hunk", () => {
    const stdout = [
      "diff --git a/src/index.ts b/src/index.ts",
      "--- a/src/index.ts",
      "+++ b/src/index.ts",
      "@@ -1,3 +1,4 @@",
      " unchanged",
      "-old line",
      "+new line",
      " still unchanged",
    ].join("\n");

    const result = parseGitDiff(stdout);
    expect(result.size).toBe(1);
    const hunks = result.get("src/index.ts");
    expect(hunks).toBeDefined();
    expect(hunks!.length).toBe(1);
    const hunk = hunks![0]!;
    expect(hunk.oldStart).toBe(1);
    expect(hunk.oldLines).toBe(3);
    expect(hunk.newStart).toBe(1);
    expect(hunk.newLines).toBe(4);
    expect(hunk.lines).toEqual([
      " unchanged",
      "-old line",
      "+new line",
      " still unchanged",
    ]);
  });

  it("parses multiple files with hunks", () => {
    const stdout = [
      "diff --git a/src/a.ts b/src/a.ts",
      "--- a/src/a.ts",
      "+++ b/src/a.ts",
      "@@ -1,2 +1,2 @@",
      " line1",
      "-old2",
      "+new2",
      "diff --git a/src/b.ts b/src/b.ts",
      "--- a/src/b.ts",
      "+++ b/src/b.ts",
      "@@ -10,3 +10,4 @@",
      " context",
      " more context",
      "+added line",
      " last context",
    ].join("\n");

    const result = parseGitDiff(stdout);
    expect(result.size).toBe(2);

    const hunksA = result.get("src/a.ts");
    expect(hunksA).toBeDefined();
    expect(hunksA!.length).toBe(1);

    const hunksB = result.get("src/b.ts");
    expect(hunksB).toBeDefined();
    expect(hunksB!.length).toBe(1);
  });

  it("skips binary files header", () => {
    const stdout = [
      "diff --git a/regular.ts b/regular.ts",
      "--- a/regular.ts",
      "+++ b/regular.ts",
      "@@ -1,1 +1,1 @@",
      "-old",
      "+new",
      "diff --git a/asset.png b/asset.png",
      "Binary files a/asset.png and b/asset.png differ",
    ].join("\n");

    const result = parseGitDiff(stdout);
    // Only the regular file should be included
    expect(result.size).toBe(1);
    expect(result.has("regular.ts")).toBe(true);
    expect(result.has("asset.png")).toBe(false);
  });

  it("skips 'index ...' lines", () => {
    const stdout = [
      "diff --git a/file.ts b/file.ts",
      "index abc123..def456 100644",
      "--- a/file.ts",
      "+++ b/file.ts",
      "@@ -1,1 +1,1 @@",
      "-old",
      "+new",
    ].join("\n");

    const result = parseGitDiff(stdout);
    expect(result.size).toBe(1);
    const hunks = result.get("file.ts");
    expect(hunks).toBeDefined();
    expect(hunks!.length).toBe(1);
    // The index line should not appear in the hunk lines
    expect(hunks![0]!.lines).toEqual(["-old", "+new"]);
  });

  it("skips '---' and '+++' lines", () => {
    const stdout = [
      "diff --git a/file.ts b/file.ts",
      "--- a/file.ts",
      "+++ b/file.ts",
      "@@ -1,1 +1,1 @@",
      "-old",
      "+new",
    ].join("\n");

    const result = parseGitDiff(stdout);
    const hunks = result.get("file.ts");
    expect(hunks![0]!.lines).toEqual(["-old", "+new"]);
  });

  it("skips 'new file' and 'deleted file' mode lines", () => {
    const stdout = [
      "diff --git a/new-file.ts b/new-file.ts",
      "new file mode 100644",
      "--- /dev/null",
      "+++ b/new-file.ts",
      "@@ -0,0 +1,2 @@",
      "+line1",
      "+line2",
    ].join("\n");

    const result = parseGitDiff(stdout);
    expect(result.size).toBe(1);
    const hunks = result.get("new-file.ts");
    expect(hunks![0]!.lines).toEqual(["+line1", "+line2"]);
  });

  it("skips 'old mode' and 'new mode' lines", () => {
    const stdout = [
      "diff --git a/script.sh b/script.sh",
      "old mode 100644",
      "new mode 100755",
      "--- a/script.sh",
      "+++ b/script.sh",
      "@@ -1,1 +1,1 @@",
      " unchanged",
    ].join("\n");

    const result = parseGitDiff(stdout);
    expect(result.size).toBe(1);
    const hunks = result.get("script.sh");
    expect(hunks![0]!.lines).toEqual([" unchanged"]);
  });

  it("parses hunk header with no count (defaults to 1)", () => {
    // @@ -1 +1 @@ means oldLines=1, newLines=1 (default when omitted)
    const stdout = [
      "diff --git a/file.ts b/file.ts",
      "--- a/file.ts",
      "+++ b/file.ts",
      "@@ -1 +1 @@",
      " unchanged",
    ].join("\n");

    const result = parseGitDiff(stdout);
    const hunks = result.get("file.ts")!;
    const hunk = hunks[0]!;
    expect(hunk.oldStart).toBe(1);
    expect(hunk.oldLines).toBe(1);
    expect(hunk.newStart).toBe(1);
    expect(hunk.newLines).toBe(1);
  });

  it("parses hunk header '@@ -1,5 +1,6 @@' correctly", () => {
    const stdout = [
      "diff --git a/file.ts b/file.ts",
      "--- a/file.ts",
      "+++ b/file.ts",
      "@@ -1,5 +1,6 @@",
      " context",
      "-old",
      "+new",
      " context",
    ].join("\n");

    const result = parseGitDiff(stdout);
    const hunk = result.get("file.ts")![0]!;
    expect(hunk.oldStart).toBe(1);
    expect(hunk.oldLines).toBe(5);
    expect(hunk.newStart).toBe(1);
    expect(hunk.newLines).toBe(6);
  });

  it("parses hunk header with large offsets", () => {
    const stdout = [
      "diff --git a/file.ts b/file.ts",
      "--- a/file.ts",
      "+++ b/file.ts",
      "@@ -1500,20 +1600,30 @@",
      " context line",
      "-removed line",
      "+added line one",
      "+added line two",
    ].join("\n");

    const result = parseGitDiff(stdout);
    const hunk = result.get("file.ts")![0]!;
    expect(hunk.oldStart).toBe(1500);
    expect(hunk.oldLines).toBe(20);
    expect(hunk.newStart).toBe(1600);
    expect(hunk.newLines).toBe(30);
  });

  it("caps files at MAX_FILES (50)", () => {
    const parts: string[] = [];
    for (let i = 0; i < 60; i++) {
      parts.push(`diff --git a/file${i}.ts b/file${i}.ts`);
      parts.push(`--- a/file${i}.ts`);
      parts.push(`+++ b/file${i}.ts`);
      parts.push("@@ -1,1 +1,1 @@");
      parts.push(` line${i}`);
    }
    const stdout = parts.join("\n");

    const result = parseGitDiff(stdout);
    expect(result.size).toBe(50);
  });

  it("includes empty lines in hunks", () => {
    const stdout = [
      "diff --git a/file.ts b/file.ts",
      "--- a/file.ts",
      "+++ b/file.ts",
      "@@ -1,3 +1,4 @@",
      " context",
      "-old",
      "+new",
      "",
    ].join("\n");

    const result = parseGitDiff(stdout);
    const hunk = result.get("file.ts")![0]!;
    // The empty line is just "" which is truthy check... wait, "" is falsy.
    // The source code checks: line.startsWith("+") || line.startsWith("-") || line.startsWith(" ") || line === ""
    // So empty lines ARE included in hunks (line === "")
    expect(hunk.lines).toContain("");
  });

  it("counts hunk lines within MAX_LINES_PER_FILE (400)", () => {
    // Create a diff where one file has exactly 400 hunk lines
    const lines: string[] = [];
    for (let i = 0; i < 410; i++) {
      lines.push(i % 2 === 0 ? `+added line ${i}` : ` context line ${i}`);
    }

    const stdout = [
      "diff --git a/large.ts b/large.ts",
      "--- a/large.ts",
      "+++ b/large.ts",
      "@@ -1,410 +1,410 @@",
      ...lines,
      "diff --git a/small.ts b/small.ts",
      "--- a/small.ts",
      "+++ b/small.ts",
      "@@ -1,1 +1,1 @@",
      " small",
    ].join("\n");

    const result = parseGitDiff(stdout);
    const largeHunk = result.get("large.ts")![0]!;
    // Should be capped at 400 lines
    expect(largeHunk.lines.length).toBeLessThanOrEqual(400);
    // The small file should still be parsed
    expect(result.has("small.ts")).toBe(true);
  });

  it("handles multiple hunks in a single file", () => {
    const stdout = [
      "diff --git a/multi.ts b/multi.ts",
      "--- a/multi.ts",
      "+++ b/multi.ts",
      "@@ -1,3 +1,3 @@",
      " line1",
      "-old2",
      "+new2",
      " line3",
      "@@ -10,3 +10,4 @@",
      " line10",
      "-removed11",
      "+added11",
      " line12",
      "+added13",
    ].join("\n");

    const result = parseGitDiff(stdout);
    expect(result.size).toBe(1);
    const hunks = result.get("multi.ts")!;
    expect(hunks.length).toBe(2);

    expect(hunks[0]!.oldStart).toBe(1);
    expect(hunks[1]!.oldStart).toBe(10);
  });

  it("skips file diffs without valid header match", () => {
    // A fileDiff that starts but has no `a/... b/...` header
    const stdout = [
      "diff --git a/valid.ts b/valid.ts",
      "--- a/valid.ts",
      "+++ b/valid.ts",
      "@@ -1,1 +1,1 @@",
      " line",
      "diff --git ",
      "garbage",
      "no header here",
    ].join("\n");

    const result = parseGitDiff(stdout);
    // Only valid.ts should be in the result
    expect(result.size).toBe(1);
    expect(result.has("valid.ts")).toBe(true);
  });

  it("handles diff without any hunks (only header)", () => {
    const stdout = [
      "diff --git a/header-only.ts b/header-only.ts",
      "index abc..def 100644",
      "--- a/header-only.ts",
      "+++ b/header-only.ts",
    ].join("\n");

    const result = parseGitDiff(stdout);
    // No hunks → file should not be in the result
    expect(result.size).toBe(0);
  });

  it("ignores lines that are not valid hunk lines after a hunk has started", () => {
    const stdout = [
      "diff --git a/file.ts b/file.ts",
      "--- a/file.ts",
      "+++ b/file.ts",
      "@@ -1,4 +1,4 @@",
      " context",
      "+added",
      "\\ No newline at end of file",
      " context",
    ].join("\n");

    const result = parseGitDiff(stdout);
    const hunk = result.get("file.ts")![0]!;
    // The \\ line should NOT be in the lines array (doesn't start with +, -, or space)
    expect(hunk.lines).toEqual([" context", "+added", " context"]);
  });
});

// ── fetchGitDiff ─────────────────────────────────────────────────────────────

describe("fetchGitDiff", () => {
  const cwdMock = "/test/repo";

  it("returns null when not in a git repo", async () => {
    // isGitRepo: rev-parse --is-inside-work-tree returns non-zero
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "fatal: not a git repository",
      128
    );

    const result = await fetchGitDiff(cwdMock);
    expect(result).toBeNull();
  });

  it("returns null when in transient state (MERGE_HEAD)", async () => {
    // isGitRepo: yes
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    // getGitDir
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    // MERGE_HEAD exists
    setAccessResult(`${cwdMock}/.git/MERGE_HEAD`, true);

    const result = await fetchGitDiff(cwdMock);
    expect(result).toBeNull();
  });

  it("returns null when in transient state (REBASE_HEAD)", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    setAccessResult(`${cwdMock}/.git/REBASE_HEAD`, true);

    const result = await fetchGitDiff(cwdMock);
    expect(result).toBeNull();
  });

  it("returns null when in transient state (CHERRY_PICK_HEAD)", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    setAccessResult(`${cwdMock}/.git/CHERRY_PICK_HEAD`, true);

    const result = await fetchGitDiff(cwdMock);
    expect(result).toBeNull();
  });

  it("returns null when in transient state (REVERT_HEAD)", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    setAccessResult(`${cwdMock}/.git/REVERT_HEAD`, true);

    const result = await fetchGitDiff(cwdMock);
    expect(result).toBeNull();
  });

  it("returns stats only when diff exceeds MAX_FILES_FOR_DETAILS (500)", async () => {
    // Setup: in repo, not transient
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    // No transient files
    // Shortstat shows >500 files
    setGitResponse(
      [
        "--no-optional-locks",
        "diff",
        "HEAD",
        "--shortstat",
      ],
      "600 files changed, 1000 insertions(+), 500 deletions(-)",
      0
    );

    const result = await fetchGitDiff(cwdMock);
    expect(result).not.toBeNull();
    expect(result!.stats).toEqual({
      filesCount: 600,
      linesAdded: 1000,
      linesRemoved: 500,
    });
    expect(result!.perFileStats.size).toBe(0);
    expect(result!.hunks.size).toBe(0);
  });

  it("returns full result for normal diff", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    // Shortstat: small diff
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--shortstat"],
      "2 files changed, 5 insertions(+), 3 deletions(-)",
      0
    );
    // Numstat
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--numstat"],
      "3\t1\tsrc/a.ts\n2\t2\tsrc/b.ts\n",
      0
    );
    // Untracked files (none)
    setGitResponse(
      ["--no-optional-locks", "ls-files", "--others", "--exclude-standard"],
      "",
      0
    );

    const result = await fetchGitDiff(cwdMock);
    expect(result).not.toBeNull();
    expect(result!.stats).toEqual({
      filesCount: 2,
      linesAdded: 5,
      linesRemoved: 3,
    });
    expect(result!.perFileStats.size).toBe(2);
    expect(result!.perFileStats.get("src/a.ts")).toEqual({
      added: 3,
      removed: 1,
      isBinary: false,
    });
    // Hunks are empty (not fetched by fetchGitDiff)
    expect(result!.hunks.size).toBe(0);
  });

  it("returns null when numstat command fails", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--shortstat"],
      "2 files changed, 5 insertions(+), 3 deletions(-)",
      0
    );
    // numstat fails
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--numstat"],
      "fatal: something went wrong",
      128
    );

    const result = await fetchGitDiff(cwdMock);
    expect(result).toBeNull();
  });

  it("includes untracked files in perFileStats with isUntracked flag", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--shortstat"],
      "1 file changed, 1 insertion(+), 0 deletions(-)",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--numstat"],
      "1\t0\tsrc/existing.ts\n",
      0
    );
    // Two untracked files
    setGitResponse(
      ["--no-optional-locks", "ls-files", "--others", "--exclude-standard"],
      "src/untracked.ts\nsrc/also-untracked.ts\n",
      0
    );

    const result = await fetchGitDiff(cwdMock);
    expect(result).not.toBeNull();
    // Stats should include untracked count
    expect(result!.stats.filesCount).toBe(3);
    expect(result!.perFileStats.size).toBe(3);
    expect(result!.perFileStats.get("src/untracked.ts")).toEqual({
      added: 0,
      removed: 0,
      isBinary: false,
      isUntracked: true,
    });
  });

  it("caps untracked files to remaining slots", async () => {
    // Create a scenario with 50 existing files (MAX_FILES) in numstat
    const numstatLines: string[] = [];
    for (let i = 0; i < 50; i++) {
      numstatLines.push(`1\t0\tsrc/file${i}.ts`);
    }

    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--shortstat"],
      "50 files changed, 50 insertions(+), 0 deletions(-)",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--numstat"],
      numstatLines.join("\n"),
      0
    );
    // Many untracked files
    const untrackedLines: string[] = [];
    for (let i = 0; i < 20; i++) {
      untrackedLines.push(`src/untracked${i}.ts`);
    }
    setGitResponse(
      ["--no-optional-locks", "ls-files", "--others", "--exclude-standard"],
      untrackedLines.join("\n"),
      0
    );

    const result = await fetchGitDiff(cwdMock);
    // perFileStats capped at 50, untracked have 0 slots
    expect(result!.perFileStats.size).toBe(50);
    // Untracked files should not be added since no slots remain
    const untrackedInResult = Array.from(result!.perFileStats.keys()).filter(
      (k) => k.includes("untracked")
    );
    expect(untrackedInResult.length).toBe(0);
  });

  it("handles untracked ls-files failure gracefully", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--shortstat"],
      "1 file changed, 1 insertion(+), 0 deletions(-)",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--numstat"],
      "1\t0\tsrc/file.ts\n",
      0
    );
    // ls-files fails
    setGitResponse(
      ["--no-optional-locks", "ls-files", "--others", "--exclude-standard"],
      "fatal: error",
      128
    );

    const result = await fetchGitDiff(cwdMock);
    expect(result).not.toBeNull();
    // Should still work, just no untracked files
    expect(result!.stats.filesCount).toBe(1);
  });

  it("handles shortstat failure (falls through to numstat)", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    // shortstat fails (code != 0)
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--shortstat"],
      "",
      1
    );
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--numstat"],
      "1\t0\tsrc/file.ts\n",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "ls-files", "--others", "--exclude-standard"],
      "",
      0
    );

    const result = await fetchGitDiff(cwdMock);
    expect(result).not.toBeNull();
    expect(result!.stats.filesCount).toBe(1);
  });

  it("handles absolute git dir paths", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    // Absolute git dir
    setGitResponse(
      ["rev-parse", "--git-dir"],
      "/absolute/path/to/.git",
      0
    );
    // No transient files at that absolute path
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--shortstat"],
      "1 file changed, 1 insertion(+), 0 deletions(-)",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD", "--numstat"],
      "1\t0\tsrc/file.ts\n",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "ls-files", "--others", "--exclude-standard"],
      "",
      0
    );

    const result = await fetchGitDiff(cwdMock);
    expect(result).not.toBeNull();
  });
});

// ── fetchGitDiffHunks ────────────────────────────────────────────────────────

describe("fetchGitDiffHunks", () => {
  const cwdMock = "/test/repo";

  it("returns empty Map when not in a git repo", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "fatal: not a git repository",
      128
    );

    const result = await fetchGitDiffHunks(cwdMock);
    expect(result).toBeInstanceOf(Map);
    expect(result.size).toBe(0);
  });

  it("returns empty Map when in transient state", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    setAccessResult(`${cwdMock}/.git/MERGE_HEAD`, true);

    const result = await fetchGitDiffHunks(cwdMock);
    expect(result).toBeInstanceOf(Map);
    expect(result.size).toBe(0);
  });

  it("returns empty Map when diff command fails", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    // No transient files
    // diff HEAD fails
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD"],
      "fatal: something went wrong",
      128
    );

    const result = await fetchGitDiffHunks(cwdMock);
    expect(result).toBeInstanceOf(Map);
    expect(result.size).toBe(0);
  });

  it("returns hunks for normal diff", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    // No transient files
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD"],
      [
        "diff --git a/src/a.ts b/src/a.ts",
        "--- a/src/a.ts",
        "+++ b/src/a.ts",
        "@@ -1,3 +1,4 @@",
        " context",
        "-old",
        "+new",
        " more context",
      ].join("\n"),
      0
    );

    const result = await fetchGitDiffHunks(cwdMock);
    expect(result.size).toBe(1);
    const hunks = result.get("src/a.ts");
    expect(hunks).toBeDefined();
    expect(hunks!.length).toBe(1);
  });

  it("parses multiple files from diff output", async () => {
    setGitResponse(
      ["rev-parse", "--is-inside-work-tree"],
      "true",
      0
    );
    setGitResponse(
      ["rev-parse", "--git-dir"],
      ".git",
      0
    );
    setGitResponse(
      ["--no-optional-locks", "diff", "HEAD"],
      [
        "diff --git a/src/a.ts b/src/a.ts",
        "--- a/src/a.ts",
        "+++ b/src/a.ts",
        "@@ -1,2 +1,2 @@",
        " line1",
        "-old2",
        "+new2",
        "diff --git a/src/b.ts b/src/b.ts",
        "--- a/src/b.ts",
        "+++ b/src/b.ts",
        "@@ -10,3 +10,4 @@",
        " context",
        "-removed",
        "+added",
        " more",
      ].join("\n"),
      0
    );

    const result = await fetchGitDiffHunks(cwdMock);
    expect(result.size).toBe(2);
    expect(result.has("src/a.ts")).toBe(true);
    expect(result.has("src/b.ts")).toBe(true);
  });
});
